# Generated by Django 3.1 on 2020-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=100)),
                ('content_html', models.TextField()),
            ],
        ),
    ]
